spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${LOCAL_DB_URL:jdbc:postgresql://localhost:5432/code_hit}
spring.datasource.username=${LOCAL_DB_USERNAME:pandacode}
spring.datasource.password=${LOCAL_DB_PASSWORD:postgreskh}

spring.jpa.hibernate.ddl-auto=${LOCAL_DDL_AUTO:create}

app.seed.enabled=${LOCAL_SEED_ENABLED:true}
app.public-base-url=${LOCAL_PUBLIC_BASE_URL:http://localhost:8001}

kakao.rest-api-key=${LOCAL_KAKAO_REST_API_KEY:d9a689a25f662f9366b1e782bce9d86e}
kakao.redirect-uri=${LOCAL_KAKAO_REDIRECT_URI:http://localhost:5173/oauth/callback/kakao}
kakao.client-secret=${LOCAL_KAKAO_CLIENT_SECRET:RWf4bxjIpvFQoz3ZgpVL0f366GqPQyrP}
naver.redirect-uri=${LOCAL_NAVER_REDIRECT_URI:http://localhost:5173/oauth/callback/naver}
google.redirect-uri=${LOCAL_GOOGLE_REDIRECT_URI:http://localhost:5173/oauth/callback/google}
