cloud.aws.s3.bucket=finalproject-s3-bucket-243050855199-ap-northeast-2-an
cloud.aws.region=ap-northeast-2

cloud.aws.credentials.access-key=AKIATRFXVXMP5DHAUSWH
cloud.aws.credentials.secret-key=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