jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create application-private.properties
        run: |
          echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application-private.properties
